doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
#            server: 'mongodb://root:test@mongo:27017/symfony'
            server: 'mongodb://%env(resolve:MONGO_USER)%:%env(resolve:MONGO_PASSWORD)%@%env(resolve:MONGO_HOST)%:27017/%env(resolve:MONGODB_DB)%'
            options:
                username: '%env(resolve:MONGO_USER)%'
                password: '%env(resolve:MONGO_PASSWORD)%'
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App\Application\Service\GameResult\Dto:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/src/Infrastructure/GameResult/Mapping/Mongo'
                    prefix: 'App\Application\Service\GameResult\Dto'
                    alias: App