version: '3.7'

services:
  apache:
    build: .docker/apache
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot
    depends_on:
      - php
    networks:
      main:
        aliases:
          - apache

  php:
    build: .docker/php
    volumes:
      - .:/home/wwwroot
    depends_on:
      - postgres
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.1.16"
      PHP_IDE_CONFIG: "serverName=scores-api"
    networks:
      main:
        aliases:
          - php

  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: "${MAIN_DB_NAME}"
      POSTGRES_USER: "${MAIN_DB_USER}"
      POSTGRES_PASSWORD: "${MAIN_DB_PASSWORD}"
    ports:
      - "${MAIN_DB_PORT}:5432"
    volumes:
      - .docker/data/db:/var/lib/postgresql
      - .docker/data/db/data:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - postgres

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_INITDB_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGODB_DB}"
    ports:
      - "${MONGO_PORT_START}-${MONGO_PORT_END}:${MONGO_PORT_START}-${MONGO_PORT_END}"
    volumes:
      - .docker/mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - .docker/data/mongo/data:/data/db
    networks:
      main:
        aliases:
          - mongo

networks:
  main:
    name: main